#!/bin/bash

if [ -f /bin/Cookie ]; then
  if grep -q "5.1" /bin/Cookie; then
    sleep 1
  else
    # comando
  fi
else
  zenity --error --text="fatal error. no Cookie file in /bin shutdown in 5 seconds error code (herobrine)" &
  sleep 5
  sudo shutdown now
fi
